// Missão prática nível 5/clientes/livros-next/src/pages/LivroDados.tsx
import type { NextPage } from 'next';
import React, { useState } from 'react';
import ControleEditora from '@/controle/ControleEditora';
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router';
import Livro from '@/modelo/Livros';
import Head from 'next/head';
import { Menu } from '@/componentes/Menu';
import ControleLivros from '@/controle/ControleLivros';

const LivroDados: NextPage = () => {
  const controleEditora: ControleEditora = new ControleEditora();
  const controleLivros = new ControleLivros();

  const [titulo, setTitulo] = useState<string>('');
  const [resumo, setResumo] = useState<string>('');
  const [autores, setAutores] = useState<string>('');
  const [codEditora, setCodEditora] = useState<number>(0);

  const router = useRouter();


  const tratarCombo = (event: React.ChangeEvent<HTMLSelectElement>): void => {
    const value = Number(event.target.value);
    setCodEditora(value);
  };

  const incluir = (event: React.FormEvent<HTMLFormElement>): void => {
    event.preventDefault();
    const livro: Livro = {
      codigo: null,
      titulo,
      resumo,
      autores: autores.split('\n'),
      codEditora
    };

    controleLivros.incluir(livro).then(() => {
      router.push('/LivroLista');
    });
  };

  const opcoes = controleEditora.getEditoras().map((editora) => ({
    value: editora.codEditora,
    text: editora.nome,
  }));

  return (
    <div className={styles.container}>
      <Head>
        <title>Livro Dados</title>
      </Head>

      <Menu />

      <main className={`${styles.main} container`}>
        <h1 className={styles.title}>Inclusão de Livro</h1>
        <form onSubmit={incluir}>
          <div className='form-group mb-4'>
            <label>Título:</label>
            <input className='form-control' type="text" value={titulo} onChange={(e) => setTitulo(e.target.value)} />
          </div>
          <div className='form-group mb-4'>
            <label>Resumo:</label>
            <textarea className='form-control' value={resumo} onChange={(e) => setResumo(e.target.value)} />
          </div>
          <div className='form-group mb-4'>
            <label>Autores:</label>
            <textarea className='form-control' value={autores} onChange={(e) => setAutores(e.target.value)} />
          </div>
          <div className='form-group mb-4'>
            <label>Editora:</label>
            <select className='form-control' value={codEditora} onChange={tratarCombo}>
              {opcoes.map((opcao) => (
                <option key={opcao.value} value={opcao.value}>
                  {opcao.text}
                </option>
              ))}
            </select>
          </div>
          <button className='btn btn-primary' type="submit">Adicionar Livro</button>
        </form>
      </main>
    </div>
  );
}

export default LivroDados

// Missão prática nível 4/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
  public livro: Livro;
  public autoresForm: string = '';
  public editoras: Array<Editora> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) {
    this.livro = new Livro(0, 0, '', '', []);
  }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = () => {
    this.livro.autores = this.autoresForm.split('\n');
    this.servLivros.incluir(this.livro);
    this.router.navigateByUrl('/lista');
  }
}

<main class="container mt-4">
  <h2>Adicionar Livro</h2>
  <form (submit)="incluir()" ngNativeValidate>
    <div class="form-group">
      <label for="titulo">Título:</label>
      <input type="text" class="form-control" id="titulo" required [(ngModel)]="livro.titulo" name="titulo">
    </div>
    <div class="form-group">
      <label for="resumo">Resumo:</label>
      <textarea class="form-control" id="resumo" required [(ngModel)]="livro.resumo" name="resumo"></textarea>
    </div>
    <div class="form-group">
      <label for="editora">Editora:</label>
      <select class="form-control" id="editora" required [(ngModel)]="livro.codEditora" name="editora">
        <option value="" disabled selected>Selecione uma editora</option>
        <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
      </select>
    </div>
    <div class="form-group">
      <label for="autores">Autores:</label>
      <textarea class="form-control" id="autores" [(ngModel)]="autoresForm" name="autores"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Adicionar Livro</button>
  </form>
</main>
