// Missão prática nível 3/livros-react/src/LivroDados.js
import React, { useState } from 'react';
import ControleEditora from './controle/ControleEditora';
import ControleLivros from './controle/ControleLivros';
import { useNavigate } from 'react-router-dom';

function LivroDados() {
  const controleLivro = new ControleLivros();
  const controleEditora = new ControleEditora();
  const navigate = useNavigate();

  const opcoes = controleEditora.getEditoras().map((editora) => ({
    value: editora.codEditora,
    text: editora.nome,
  }));

  const [titulo, setTitulo] = useState('');
  const [resumo, setResumo] = useState('');
  const [autores, setAutores] = useState('');
  const [codEditora, setCodEditora] = useState(opcoes[0].value);

  const tratarCombo = (event) => {
    setCodEditora(Number(event.target.value));
  };

  const incluir = (event) => {
    event.preventDefault();
    const novoLivro = {
      codigo: 0,
      codEditora: codEditora,
      titulo: titulo,
      resumo: resumo,
      autores: autores.split('\n').map((autor) => autor.trim()),
    };
    controleLivro.incluir(novoLivro);
    navigate('/');
  };

  return (
    <main className='mx-4'>
      <h1>Cadastro de Livro</h1>
      <form onSubmit={incluir}>
        <div className='form-group mb-4'>
          <label>Título:</label>
          <input
            className='form-control'
            type="text"
            value={titulo}
            onChange={(e) => setTitulo(e.target.value)}
          />
        </div>
        <div className='form-group mb-4'>
          <label>Resumo:</label>
          <textarea
            className='form-control'
            value={resumo}
            onChange={(e) => setResumo(e.target.value)}
          ></textarea>
        </div>
        <div className='form-group mb-4'>
          <label>Editora:</label>
          <select className='form-control' value={codEditora} onChange={tratarCombo}>
            {opcoes.map((opcao) => (
              <option key={opcao.value} value={opcao.value}>
                {opcao.text}
              </option>
            ))}
          </select>
        </div>
        <div className='form-group mb-4'>
          <label>Autores (1 por linha):</label>
          <textarea
            className='form-control'
            value={autores}
            onChange={(e) => setAutores(e.target.value)}
          ></textarea>
        </div>
        <div className='form-group'>
          <button className='btn btn-primary' type="submit">Adicionar Livro</button>
        </div>
      </form>
    </main>
  );
}

export default LivroDados;

// Missão prática nível 4/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
  public livro: Livro;
  public autoresForm: string = '';
  public editoras: Array<Editora> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) {
    this.livro = new Livro(0, 0, '', '', []);
  }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = () => {
    this.livro.autores = this.autoresForm.split('\n');
    this.servLivros.incluir(this.livro);
    this.router.navigateByUrl('/lista');
  }
}

<main class="container mt-4">
  <h2>Adicionar Livro</h2>
  <form (submit)="incluir()" ngNativeValidate>
    <div class="form-group">
      <label for="titulo">Título:</label>
      <input type="text" class="form-control" id="titulo" required [(ngModel)]="livro.titulo" name="titulo">
    </div>
    <div class="form-group">
      <label for="resumo">Resumo:</label>
      <textarea class="form-control" id="resumo" required [(ngModel)]="livro.resumo" name="resumo"></textarea>
    </div>
    <div class="form-group">
      <label for="editora">Editora:</label>
      <select class="form-control" id="editora" required [(ngModel)]="livro.codEditora" name="editora">
        <option value="" disabled selected>Selecione uma editora</option>
        <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
      </select>
    </div>
    <div class="form-group">
      <label for="autores">Autores:</label>
      <textarea class="form-control" id="autores" [(ngModel)]="autoresForm" name="autores"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Adicionar Livro</button>
  </form>
</main>
